# Generated by Django 5.1 on 2024-08-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_peliculas_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='Saga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='myapp.saga'),
        ),
    ]
