# Generated by Django 5.1 on 2024-08-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_peliculas_vista_pelicula_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
