# Generated by Django 5.1 on 2024-08-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_peliculas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
