# Generated by Django 5.1 on 2024-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_peliculas_saga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='Saga',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='genere',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Saga',
        ),
    ]
