# Generated by Django 5.1 on 2024-08-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_peliculas_saga_peliculas_genere_delete_saga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='genere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
