# Generated by Django 5.1 on 2024-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_peliculas_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
